# Generated by Django 2.2.5 on 2020-01-08 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20191029_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
